name = "add-client-ip-ec2-security-group"
type = "javascript"
account_id = "b9920038e182e4f7f60649b0794d5914"
workers_dev = true
compatibility_date = "2021-09-30"
send_metrics = true

[build]
command = "pnpm install && pnpm run build"

[build.upload]
format = "service-worker"

[vars]
AWS_ACCESS_KEY = "a"
AWS_REGION = "ap-northeast-1"
AWS_SECRET_KEY = "a"
AWS_SECURITY_GROUP_ID = "a"
REMOTE_PORT = "9910"
